### ISSUE TITLE
Install (Torch) and Run (Transformers) Issues

### ISSUE THREAD

**Issue by mkammes** [cocktailpeanut/ms-video2video.pinokio#2]
Install Issue:
```
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0+cu118
    Uninstalling torch-2.1.0+cu118:
      Successfully uninstalled torch-2.1.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.22.post4+cu118 requires torch==2.1.0, but you have torch 2.1.1+cu118 which is incompatible.
Successfully installed torch-2.1.1+cu118
```
Run Issue:

```
(env) C:\Users\micha\pinokio\api\ms-video2video.pinokio.git>python app.py
2023-12-14 12:04:15,425 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-14 12:04:15,428 - modelscope - INFO - Loading ast index from C:\Users\micha\.cache\modelscope\ast_indexer
2023-12-14 12:04:15,552 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 900bb53301c562f3402b58da8ebfa5c1 and a total number of 946 components indexed
2023-12-14 12:04:18,734 - modelscope - INFO - Model revision not specified, use default: master in development mode
2023-12-14 12:04:18,734 - modelscope - INFO - Development mode use revision: master
Traceback (most recent call last):
  File "C:\Users\micha\pinokio\api\ms-video2video.pinokio.git\app.py", line 6, in <module>
    pipe = pipeline(task='video-to-video', model='damo/Video-to-Video')#, model_revision='v1.1.0')
  File "c:\users\micha\pinokio\api\ms-video2video.pinokio.git\modelscope\package\modelscope\pipelines\builder.py", line 163, in pipeline
    clear_llm_info(kwargs)
  File "c:\users\micha\pinokio\api\ms-video2video.pinokio.git\modelscope\package\modelscope\pipelines\builder.py", line 227, in clear_llm_info
    from .nlp.llm_pipeline import ModelTypeHelper
  File "c:\users\micha\pinokio\api\ms-video2video.pinokio.git\modelscope\package\modelscope\pipelines\nlp\llm_pipeline.py", line 9, in <module>
    from transformers import PreTrainedTokenizer
ModuleNotFoundError: No module named 'transformers'
```

Pinokio Version 0.2.7 
(Server: 0.0.421)
Win 11 Pro (22H3)
i7-8700 @3.7GHz
64GB RAM
4070 TI

**Comment by Andro-Meta** [comment]
I'm updated to the newest version of Pinokio and having the same issues.
